---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: Install epel-release for CentOS
    yum:
      name:
        - epel-release
    when: ansible_distribution == "CentOS"


- hosts: CentOS_server
  become: true
  roles:
    - CentOS_server

- hosts: Ubuntu_server
  become: true
  roles:
    - Ubuntu_server
